name: Chromatic

on:
  push:
    paths: ["src/**"]

jobs:
  chromatic:
    name: Chromatic Visual Tests 🌈
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chromatic skip') && !contains(github.event.head_commit.message, 'skip chromatic')"
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node Modules
        id: node-modules
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-npm_directory-${{ github.head_ref }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Publish to Chromatic 🚀
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
