name: Chromatic

on: push

jobs:
  chromatic:
    name: Chromatic Visual Tests 🌈
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chromatic skip') && !contains(github.event.head_commit.message, 'skip chromatic')"
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'

      - name: Cache Node Modules
        if: steps.changes.outputs.src == 'true'
        id: node-modules
        uses: actions/cache@v1
        with:
          path: ui/node_modules/
          key: ${{ runner.os }}-npm_directory-${{ github.head_ref }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.changes.outputs.src == 'true' && steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Publish to Chromatic 🚀
        if: steps.changes.outputs.src == 'true'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
